name: isma
description: Final Calculator

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.1.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  provider:
  path_provider: ^2.0.13
  flutter_svg:
  path:
  permission_handler:
  flutter_animate:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: text
      fonts:
        - asset: assets/font/LineB.ttf
          weight: 700
        - asset: assets/font/LineR.ttf
          weight: 500
        - asset: assets/font/LineT.ttf
  assets:
    - assets/
    - assets/icon/